[package]
edition = "2024"
name = "client"
version = "0.1.0"

[[bin]]
name = "client"

[dependencies]
anyhow = { workspace = true }
fake = { workspace = true }
model = { workspace = true }
sercli = { workspace = true }
tokio = { workspace = true }

server = { workspace = true }
