[package]
edition = "2021"
name = "client"
version = "0.1.0"

[[bin]]
name = "client"

[dependencies]
anyhow = { workspace = true }
model = { workspace = true }
reflected = { workspace = true }
sercli = { workspace = true }
tokio = { workspace = true }
