[package]
edition = "2021"
name = "model"
version = "0.1.0"

[lib]
crate-type = ["rlib", "staticlib"]
name = "model"

[dependencies]
reflected = { workspace = true }
sercli = { workspace = true }
serde = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
sercli = { workspace = true }
