[workspace]
default-members = ["sercli"]
members = ["sercli", "model", "server", "client"]

resolver = "2"

[workspace.metadata.cargo-machete]
ignored = []

[workspace.dependencies]
actix-web = "4.8"
anyhow = "1.0"
log = "0.4"
reflected = "0.10.1"
reqwest = { version = "0.12.5", default-features = false, features = ["rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.39", features = ["macros", "rt-multi-thread"] }

model = { path = "model" }
sercli = { path = "sercli" }
