[workspace]
default-members = ["sercli"]
members = ["sercli", "model", "server", "client"]

resolver = "2"

[workspace.metadata.cargo-machete]
ignored = []

[workspace.dependencies]
anyhow = "1.0"
axum = { version = "0.7.5" }
log = "0.4"
axum-login = "0.16"
reflected = "0.10"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1"
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres"] }
tokio = { version = "1.39", features = ["macros", "rt-multi-thread"] }
password-auth = "1.1.0-pre.1"
sqlparser = "0.51"

tain = "0.4.0"

model = { path = "model" }
server = { path = "server" }

sercli = { path = "sercli" }

[patch.crates-io]
#tain = { path = "../tain/tain" }
