services:
  pg:
    image: postgres:17-alpine
    command: postgres -c max_connections=1000
    environment:
      POSTGRES_USER: sercli
      POSTGRES_PASSWORD: sercli
      POSTGRES_DB: sercli_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 54321:5432

volumes:
  postgres_data:
