name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        target: [
          { os: macos, runner: macos-latest, },
          #            { os: windows , runner: windows-latest },
          #
          #          { os: ios, runner: mac },
          #          { os: android, runner: ubuntu-latest },
        ]
    runs-on: ${{ matrix.target.runner }}
    steps:
      - name: Setup docker (missing on MacOS)
        if: runner.os == 'macos'
        run: |
          brew install docker
          colima start  

      - uses: actions/checkout@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          submodules: recursive

      - name: Lint
        run: make lint

      - name: Test
        run: make test

  linux:
    name: Build Linux
    strategy:
      fail-fast: false
      matrix:
        target: [
          { container: "ubuntu" },
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          submodules: recursive

      - name: Lint
        run: make lint

      - name: Test
        run: echo ${{ matrix.target.container }} && make test
